### ISSUE TITLE
erreur lors de l'installation

### ISSUE THREAD

**Issue by Philippe-dev** [franck-paul/dmHostingMonitor#1]
Dotclear 2.24-dev dernière version, PHP 8.1, en local
J'ai tenté l'installation du plugin, mais il est automatiquement désactivé avec un message demandant l'installation de Dashboard Module Helper Library 1.0
Problème : lorsque je clique sur Gestion des plugins, l'erreur suivante apparaît 

```
Warning: Undefined array key "version" in /var/www/dotclear.unstable.local/htdocs/dotclear/inc/core/class.dc.store.php on line 106

Fatal error: Uncaught TypeError: dcUtils::versionsCompare(): Argument #2 ($required_version) must be of type string, null given, called in /.../dotclear/inc/core/class.dc.store.php on line 106 and defined in /.../dotclear/inc/core/class.dc.utils.php:128 Stack trace: #0 /.../dotclear/inc/core/class.dc.store.php(106): dcUtils::versionsCompare() #1 /.../dotclear/inc/core/class.dc.store.php(71): dcStore->check() #2 /.../dotclear/inc/admin/lib.moduleslist.php(168): dcStore->__construct() #3 /.../dotclear/admin/plugins.php(25): adminModulesList->__construct() #4 /.../dotclear/admin/plugins.php(306): adminPlugins::init() #5 {main} thrown in /.../dotclear/inc/core/class.dc.utils.php on line 128
```
Seule solution : supprimer le répertoire du plugin

**Comment by franck-paul** [comment]
Problème repéré (et corrigé) du côté Dotclear.
